#!/usr/bin/env python3
"""
run_dp_sweep.py
---------------
Sweeps the privacy budget epsilon across mechanisms and partitions, producing
the privacy-utility table that is HW6's headline result.

It shells out to run_simulation.py once per configuration rather than importing
it, so every point in the sweep is generated by exactly the same code path a
grader would run by hand -- no separate "sweep-only" execution route that could
silently diverge from the single-run one.

eps = inf is encoded as `--dp none`, which reproduces the HW5 configuration and
anchors the curve: every DP point should be read as a drop from that baseline.

Usage:
    # the headline sweep (IID, all three mechanisms)
    python3 run_dp_sweep.py --partition iid --n-seeds 3

    # quick smoke test of the whole grid
    python3 run_dp_sweep.py --rounds 5 --n-seeds 1 --epsilons 8
"""

import argparse
import itertools
import json
import subprocess
import sys
from pathlib import Path

# Mechanisms compared. The trust model is the axis that matters -- see dp.py.
MECHANISMS = [
    ("none",           "No DP (HW5 baseline)",              "-"),
    ("central_server", "Central DP, server-side clipping",  "trusts server"),
    ("central_client", "Central DP, client-side clipping",  "trusts server for noise only"),
    ("local",          "Local DP",                          "trusts nobody"),
    ("dpsgd",          "DP-SGD (sample-level)",             "per-example"),
]

DEFAULT_EPSILONS = [0.5, 1.0, 2.0, 4.0, 8.0]


def run_one(args, mechanism, epsilon):
    """Run a single configuration, return its summary dict (or None on failure)."""
    tag = "none" if mechanism == "none" else f"{mechanism}_eps{epsilon}"
    dp_prefix = "dp" if args.dataset == "cape" else f"dp_{args.dataset}"
    out = Path(args.outdir) / f"{dp_prefix}_{args.partition}_{tag}.json"

    # Each config's own result file is that config's checkpoint: a full sweep
    # takes hours, and re-running finished configs after an interrupted sweep
    # would waste most of that. --force re-runs anyway (e.g. changed hyperparams).
    if out.exists() and not args.force:
        print(f"  -> {mechanism:<15} eps={epsilon if mechanism != 'none' else 'inf'}  "
              f"(skipped, found {out})", flush=True)
        with open(out) as f:
            return json.load(f)

    cmd = [
        sys.executable, "run_simulation.py",
        "--dataset", args.dataset,
        "--partition", args.partition,
        "--num-clients", str(args.num_clients),
        "--rounds", str(args.rounds),
        "--local-epochs", str(args.local_epochs),
        "--lr", str(args.lr),
        "--optimizer", args.optimizer,
        "--n-seeds", str(args.n_seeds),
        "--clip", str(args.clip),
        "--dp", mechanism,
        "--out", str(out),
    ]
    if args.dataset == "public":
        cmd += ["--test-frac", str(args.test_frac), "--split-seed", str(args.split_seed)]
    if mechanism != "none":
        cmd += ["--epsilon", str(epsilon)]

    print(f"  -> {mechanism:<15} eps={epsilon if mechanism != 'none' else 'inf'}", flush=True)
    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        print(f"     FAILED (exit {proc.returncode})")
        print("     " + proc.stderr.strip().splitlines()[-1][:200] if proc.stderr else "")
        return None

    with open(out) as f:
        return json.load(f)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dataset", choices=["cape", "public"], default="cape")
    ap.add_argument("--test-frac", type=float, default=0.2,
                     help="public dataset only, forwarded to run_simulation.py")
    ap.add_argument("--split-seed", type=int, default=0,
                     help="public dataset only, forwarded to run_simulation.py")
    ap.add_argument("--partition", choices=["iid", "non_iid"], default="iid")
    ap.add_argument("--mechanisms", nargs="*", default=None,
                    help="subset of mechanism names; default all")
    ap.add_argument("--epsilons", nargs="*", type=float, default=None)
    ap.add_argument("--num-clients", type=int, default=3)
    ap.add_argument("--rounds", type=int, default=40)
    ap.add_argument("--local-epochs", type=int, default=2)
    ap.add_argument("--lr", type=float, default=1e-2)
    ap.add_argument("--clip", type=float, default=1.0)
    # SGD by default: a diverging Adam baseline would make it impossible to
    # attribute an accuracy drop to the DP noise rather than to the optimiser.
    ap.add_argument("--optimizer", choices=["adam", "sgd"], default="sgd")
    ap.add_argument("--n-seeds", type=int, default=3)
    ap.add_argument("--outdir", default="results")
    ap.add_argument("--summary", default=None)
    ap.add_argument("--force", action="store_true",
                     help="re-run every config even if its result file already "
                          "exists (default: skip and reuse it -- resume support "
                          "for an interrupted sweep)")
    args = ap.parse_args()

    epsilons = args.epsilons or DEFAULT_EPSILONS
    mechs = [m for m in MECHANISMS
             if args.mechanisms is None or m[0] in args.mechanisms]
    if args.summary is None:
        sweep_prefix = "dp_sweep" if args.dataset == "cape" else f"dp_sweep_{args.dataset}"
        args.summary = f"{args.outdir}/{sweep_prefix}_{args.partition}.json"

    Path(args.outdir).mkdir(parents=True, exist_ok=True)

    # eps is meaningless without DP, so the baseline runs exactly once.
    jobs = []
    for mech, label, trust in mechs:
        if mech == "none":
            jobs.append((mech, label, trust, None))
        else:
            jobs += [(mech, label, trust, e) for e in epsilons]

    print(f"[+] DP sweep: partition={args.partition}, {len(jobs)} configurations, "
          f"{args.rounds} rounds x {args.n_seeds} seeds each")

    rows = []
    n_families = None
    for mech, label, trust, eps in jobs:
        summary = run_one(args, mech, eps)
        if summary is None:
            continue
        if n_families is None:
            n_families = len(summary.get("families", [])) or 3
        rows.append({
            "mechanism": mech,
            "label": label,
            "trust_model": trust,
            "epsilon": eps,
            "privacy_unit": summary.get("dp", {}).get("privacy_unit", "-"),
            "noise_multiplier": summary.get("dp", {}).get("noise_multiplier", 0.0),
            "epsilon_actual": summary.get("dp", {}).get("epsilon_actual"),
            "delta": summary.get("dp", {}).get("delta"),
            "sample_accuracy": summary["sample_level_accuracy"],
            "sample_std": summary["sample_level_std"],
            "window_accuracy": summary["window_level_accuracy"],
            "window_std": summary["window_level_std"],
        })

    baseline = next((r["sample_accuracy"] for r in rows if r["mechanism"] == "none"), None)
    for r in rows:
        # "fraction of the no-DP accuracy retained" is only meaningful when the
        # baseline actually learned something; a zero baseline makes the ratio
        # undefined rather than 0, and reporting 0 would imply DP caused a drop
        # that was never there to cause.
        r["accuracy_retained"] = (round(r["sample_accuracy"] / baseline, 3)
                                  if baseline else None)

    out = {
        "sweep": f"dp_{args.partition}",
        "partition": args.partition,
        "config": vars(args),
        "baseline_accuracy": baseline,
        "rows": rows,
    }
    with open(args.summary, "w") as f:
        json.dump(out, f, indent=2)

    # ---- printed table, ready to paste into the report --------------------
    print(f"\n{'mechanism':<16}{'eps':>6}{'unit':>8}{'z':>9}"
          f"{'accuracy':>12}{'retained':>10}")
    print("-" * 61)
    for r in rows:
        eps = "inf" if r["epsilon"] is None else f"{r['epsilon']:g}"
        ret = "-" if r["accuracy_retained"] is None else f"{r['accuracy_retained']:.2f}"
        print(f"{r['mechanism']:<16}{eps:>6}{r['privacy_unit']:>8}"
              f"{r['noise_multiplier']:>9.2f}"
              f"{r['sample_accuracy']:>8.2f}+/-{r['sample_std']:.2f}{ret:>10}")

    print(f"\n[+] written to {args.summary}")
    chance = 1.0 / n_families if n_families else 1.0 / 3
    if baseline is not None and baseline <= chance + 1e-9:
        print(f"\n[!] The no-DP baseline is at or below chance (1/{n_families} for "
              f"{n_families} classes).")
        print("    Every DP point below it is therefore uninformative: noise cannot")
        print("    degrade a model that has not learned anything."
              + ("" if args.dataset == "public" else
                 " Run this sweep with --dataset public for a meaningful curve."))


if __name__ == "__main__":
    main()
